[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = ["./gradlew clean build -x test"]

[phases.install]
cmds = ["echo 'Build completed'"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/city-reporter-backend-0.0.1-SNAPSHOT.jar"
